import { StartSessionPayloadSchema, ulid } from '@ironyard/shared';
import type { CampaignState, IntentResult, StampedIntent } from '../types';

// Notes:
//   - approved-character validation is the DO stamper's job (it reads D1);
//     the reducer trusts what's on the stamped payload.
//   - the canonical session id is generated by the reducer via ulid() when
//     no client-suggested id is provided. Client SHOULD provide one (same
//     pattern as StartEncounter.encounterId) so the optimistic mirror picks
//     it up without a snapshot round-trip.
//   - default name 'Session N' is set by the stamper from D1's session count;
//     the reducer falls back to 'Session' if name is omitted (defensive).
export function applyStartSession(state: CampaignState, intent: StampedIntent): IntentResult {
  const parsed = StartSessionPayloadSchema.safeParse(intent.payload);
  if (!parsed.success) {
    return {
      state,
      derived: [],
      log: [
        {
          kind: 'error',
          text: `StartSession rejected: ${parsed.error.message}`,
          intentId: intent.id,
        },
      ],
      errors: [{ code: 'invalid_payload', message: parsed.error.message }],
    };
  }
  if (state.currentSessionId !== null) {
    return {
      state,
      derived: [],
      log: [{ kind: 'error', text: 'session already active', intentId: intent.id }],
      errors: [
        { code: 'session_already_active', message: 'end the active session first' },
      ],
    };
  }

  const { sessionId: suggestedId, name, attendingCharacterIds, heroTokens } = parsed.data;
  const sessionId = suggestedId ?? `sess_${ulid()}`;
  const tokens = heroTokens ?? attendingCharacterIds.length;
  const sessionName = name ?? 'Session';

  return {
    state: {
      ...state,
      seq: state.seq + 1,
      currentSessionId: sessionId,
      attendingCharacterIds: [...attendingCharacterIds],
      heroTokens: tokens,
    },
    derived: [],
    log: [
      {
        kind: 'info',
        text: `session ${sessionId} (${sessionName}) started with ${attendingCharacterIds.length} attending, ${tokens} hero token(s)`,
        intentId: intent.id,
      },
    ],
  };
}
