// The rules engine. Pure, stateless. Same code runs in the DO and the client.
//
// Phase 0 item 2 adds:
//   - canon-status.generated.ts (generated by scripts/gen-canon-status.ts)
//   - requireCanon(slug) — gates auto-application on '✅ verified' status
//
// Phase 1 adds:
//   - applyIntent(state, intent) — the dispatcher
//   - inverse(intent, stateBefore) — for undo
//   - canDispatch(intent, actor, state) — permissions
//   - intents/, conditions/, resources/, damage.ts, rolls.ts, turn-state.ts, etc.

export const PACKAGE = '@ironyard/rules' as const;
